### ISSUE TITLE
Docker login command compatible with docker 18.04

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal-cli-v2#10]
Souvisí s https://github.com/keboola/connection/pull/1311

Docker `18.04` vyhazuje confirm dialog kvůli credentials storage https://github.com/docker/docker-ce/releases/tag/v18.04.0-ce a tím blokne build.

**Comment by odinuv** [comment]
Zkousim to na 18.09 a zadnej dialog to nevyhazuje, akorat warning, nezmenili to zase?

**Comment by Halama** [comment]
to je možné že se to změnilo. pokud ti to teda projde ok tak se tohle může zavřít.
