### ISSUE TITLE
Add update App command

### ISSUE THREAD

**Issue by davidesner** [keboola/developer-portal-cli-v2#11]
Would it be possible to add a command that could update any attribute in the app config? Mainly `configurationSchema`, `configurationDescription`,`testConfiguration`...

These could be added to the `update-app-repository` command I think. Or maybe allow to input the full json as a parameter?

It would be useful for CI to sync app configuration directly from the git repository.

**Comment by odinuv** [comment]
`update-app-repository` does what the name says, so let's add a new command for this.
I don't think that passing jsons via command line arguments is a good idea - you need to deal with escaping a lot of special characters and you can hit some weird limits, so i'd say it should be able to read those from files

**Comment by odinuv** [comment]
done in 179e2cf, new command `update-app-property` allows both to enter a value via command line and read the value from file.
