### ISSUE TITLE
command to inspect component version

### ISSUE THREAD

**Issue by fprochazka** [keboola/developer-portal-cli-v2#22]
Hi,
I'm trying to publish a component and I'm struggling with tagging a new version. I do not want to tag the git repository to have a "source" for the component's tag, so I have to choose the version with alternative means. I've figured, that I can query the components portal, get the latest published version from there, increase minor version and publish new version.

Right now, I'm doing this: 

```bash
increaseMinorVersion () {
	a=( ${1//./ } )
	((a[1]++))
	echo "${a[0]}.${a[1]}.${a[2]:-0}"
}

KEBOOLA_LOGIN_DATA="{\"email\":\"${KBC_DEVELOPERPORTAL_USERNAME}\",\"password\":\"${KBC_DEVELOPERPORTAL_PASSWORD}\"}"
KEBOOLA_APPS_TOKEN=$(curl -q -s 'https://apps-api.keboola.com/auth/login' -H 'Accept: application/json' --data "${KEBOOLA_LOGIN_DATA}" | jq -r '.token')
LAST_PUBLISHED_VERSION=$(curl -q -s "https://apps-api.keboola.com/vendors/${KBC_DEVELOPERPORTAL_VENDOR}/apps/${KBC_DEVELOPERPORTAL_APP}" -H 'Accept: application/json' -H "Authorization: ${KEBOOLA_APPS_TOKEN}" | jq -r '.repository.tag')

export RELEASE_VERSION=$(increaseMinorVersion "${LAST_PUBLISHED_VERSION}")

docker tag "${MY_IMAGE}" "${KEBOOLA_REPOSITORY}:${RELEASE_VERSION}"

# ... 
```

If I had a cli command to query the portal, this could be bit simpler 

```bash
LAST_PUBLISHED_VERSION=$(kbc-dev-portal get-app-last-version ${KBC_DEVELOPERPORTAL_VENDOR} ${KBC_DEVELOPERPORTAL_APP})
```

I know this kind of breaks the semantic versioning, but it's automation-friendly, and I don't really care about semver here, since it's a private component 

If this addition makes sense to you, I might be willing to contribute the command, but no promises :)  

Thanks!

**Comment by ujovlado** [comment]
Hi Filip,

> If this addition makes sense to you, I might be willing to contribute the command, but no promises :)

It does make sense, but I would prefer to make it as specific as possible. So command named `app:get-repository-tag`, or even better `component:get-repository-tag` (because they are components, not apps anymore) would be perfect.

You can take `GetRepository.php` as inspiration (it takes 2 arguments) and tune execute method to something like:

```php
$component = $client->getAppDetail($input->getArgument('vendor'), $input->getArgument('app'));
$output->writeln($component['repository']['tag']);
```
In the meantime we will try to fix the build process (migrate to Github Actions), so we'll be able to release new version of the CLI tool. 😉

**Comment by ujovlado** [comment]
@fprochazka so it landed there as `get-app-repository-tag` (due to consistency), feel free to test it.

**Comment by fprochazka** [comment]
Works great, thanks!
